#Requires -Version 5.1
<#
  export.ps1 -- snapshot live ~/.openclaw/openclaw.json into repo
  openclaw.template.json with secrets stripped.
  ALWAYS review the diff (git diff) before committing.
  Stripped: gateway.auth.token, auth profiles, channels.*.allowFrom,
  wizard block, telemetry timestamps. Model primary normalized to openrouter/auto.
  Non-stock plugin specs live in plugins.txt (maintained by hand; reminder printed).
#>
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$Live = Join-Path $HOME ".openclaw\openclaw.json"
$Out = Join-Path $RepoRoot "openclaw.template.json"
if (-not (Test-Path $Live)) { throw "live config not found: $Live" }

$cfg = Get-Content $Live -Raw | ConvertFrom-Json
if ($cfg.gateway.auth) { $cfg.gateway.auth.PSObject.Properties.Remove('token') }
$cfg.PSObject.Properties.Remove('wizard')
$cfg.PSObject.Properties.Remove('auth')
if ($cfg.telemetry) { $cfg.telemetry.PSObject.Properties.Remove('consentedAt') }
if ($cfg.channels.whatsapp) { $cfg.channels.whatsapp.PSObject.Properties.Remove('allowFrom') }
$cfg.agents.defaults.model.primary = 'openrouter/auto'

$header = @(
  '// snarlis/openclaw -- sanitized snapshot of ~/.openclaw/openclaw.json (JSON5 allowed).',
  ('// Exported {0} via scripts/export.ps1. REVIEW THE DIFF BEFORE COMMITTING.' -f (Get-Date -Format 'yyyy-MM-dd')),
  '// STRIPPED: gateway token (regenerated by doctor --fix), auth profiles (re-login),',
  '// whatsapp allowFrom (re-pair via `openclaw channels add`), timestamps.',
  '// Restore: copy to ~/.openclaw/openclaw.json or run scripts/setup.ps1.'
)
$json = $cfg | ConvertTo-Json -Depth 30
($header + @($json)) | Set-Content $Out -Encoding UTF8
Write-Host "wrote $Out -- review with: git diff"

Write-Host ''
Write-Host 'Plugin IDs referenced in live config (keep plugins.txt specs in sync):'
$cfg.plugins.entries.PSObject.Properties.Name | ForEach-Object { Write-Host "  - $_" }
